### ISSUE TITLE
Possible error in bin/digest_and_ingest.sh file?

### ISSUE THREAD

**Issue by deadjoe2002** [saitomics/metatryp#1]
Hello,

I was having trouble running the digest_and_ingest script where I was getting a ' proteomics.digest_and_ingest.py module not found' error. I managed to get it working by changing the digest_and_ingest.sh file to call the 'proteomics.scripts.digest_and_ingest.py' python file as opposed to the 'proteomics.digest_and_ingest.py' which doesn't seem to exist. Not sure if this was just my setup but thought it might be worth mentioning to anyone else having issues.

Joe

**Comment by adorsk** [comment]
Hi @deadjoe2002 ,

Thanks for letting us know about this. I'll check this out sometime in the next few days.

-Alex

**Comment by adorsk** [comment]
@deadjoe2002 , Thanks for pointing this out, should be fixed with this commit: https://github.com/saitomics/metatryp/commit/9feca7c664a1811b34cecd8fc883ed628f68f40a .

Btw, I'm curious, what sort of stuff are you using metatryp for? We're tickled that other folks are checking it out.
